version: '3.9'
services:
  mysqldb:
    build: ./mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=mydb
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network
  node:
    restart: on-failure
    build: ./node
    ports:
      - '81:5000'
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=mydb
      - DB_PORT=3306
    depends_on:
    - mysqldb
    networks:
      - app-network
  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - node
    networks:
      - app-network

volumes:
  db:
networks:
    app-network:
        driver: bridge